//
// ErrorModel.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ErrorModel: Codable, JSONEncodable, Hashable {

    public var error: String
    public var code: Int

    public init(error: String, code: Int) {
        self.error = error
        self.code = code
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case error
        case code
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(error, forKey: .error)
        try container.encode(code, forKey: .code)
    }
}

