//
// TitleGet200ResponseDocsInnerPoster.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TitleGet200ResponseDocsInnerPoster: Codable, JSONEncodable, Hashable {

    public var url: String
    public var previewUrl: String

    public init(url: String, previewUrl: String) {
        self.url = url
        self.previewUrl = previewUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case url
        case previewUrl
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(url, forKey: .url)
        try container.encode(previewUrl, forKey: .previewUrl)
    }
}

