//
// TitleGet200ResponseDocsInnerExternalId.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TitleGet200ResponseDocsInnerExternalId: Codable, JSONEncodable, Hashable {

    public var kpHD: String
    public var imdb: String
    public var tmdb: Double

    public init(kpHD: String, imdb: String, tmdb: Double) {
        self.kpHD = kpHD
        self.imdb = imdb
        self.tmdb = tmdb
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case kpHD
        case imdb
        case tmdb
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(kpHD, forKey: .kpHD)
        try container.encode(imdb, forKey: .imdb)
        try container.encode(tmdb, forKey: .tmdb)
    }
}

