//
// TitleGet200ResponseDocsInnerSeasonsInfoInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TitleGet200ResponseDocsInnerSeasonsInfoInner: Codable, JSONEncodable, Hashable {

    public var number: Double?
    public var episodesCount: Double?

    public init(number: Double? = nil, episodesCount: Double? = nil) {
        self.number = number
        self.episodesCount = episodesCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case number
        case episodesCount
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(number, forKey: .number)
        try container.encodeIfPresent(episodesCount, forKey: .episodesCount)
    }
}

