//
// TitleGet200ResponseDocsInnerVideosTrailersInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TitleGet200ResponseDocsInnerVideosTrailersInner: Codable, JSONEncodable, Hashable {

    public var url: String?
    public var name: String?
    public var site: String?
    public var size: Double?
    public var type: String?

    public init(url: String? = nil, name: String? = nil, site: String? = nil, size: Double? = nil, type: String? = nil) {
        self.url = url
        self.name = name
        self.site = site
        self.size = size
        self.type = type
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case url
        case name
        case site
        case size
        case type
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(url, forKey: .url)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(site, forKey: .site)
        try container.encodeIfPresent(size, forKey: .size)
        try container.encodeIfPresent(type, forKey: .type)
    }
}

