//
// TitleGet200ResponseDocsInnerNetworksItemsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TitleGet200ResponseDocsInnerNetworksItemsInner: Codable, JSONEncodable, Hashable {

    public var name: String?
    public var logo: TitleGet200ResponseDocsInnerLogo?

    public init(name: String? = nil, logo: TitleGet200ResponseDocsInnerLogo? = nil) {
        self.name = name
        self.logo = logo
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case logo
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(logo, forKey: .logo)
    }
}

