//
// TitleGet200ResponseDocsInnerNamesInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TitleGet200ResponseDocsInnerNamesInner: Codable, JSONEncodable, Hashable {

    public var name: String?
    public var language: String?
    public var type: String?

    public init(name: String? = nil, language: String? = nil, type: String? = nil) {
        self.name = name
        self.language = language
        self.type = type
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case language
        case type
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(language, forKey: .language)
        try container.encodeIfPresent(type, forKey: .type)
    }
}

