//
// TitleGet200ResponseDocsInnerBudget.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TitleGet200ResponseDocsInnerBudget: Codable, JSONEncodable, Hashable {

    public var value: Double
    public var currency: String

    public init(value: Double, currency: String) {
        self.value = value
        self.currency = currency
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case value
        case currency
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(value, forKey: .value)
        try container.encode(currency, forKey: .currency)
    }
}

