//
// TitleGet200ResponseDocsInnerAudienceInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TitleGet200ResponseDocsInnerAudienceInner: Codable, JSONEncodable, Hashable {

    public var count: Double?
    public var country: String?

    public init(count: Double? = nil, country: String? = nil) {
        self.count = count
        self.country = country
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case count
        case country
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(count, forKey: .count)
        try container.encodeIfPresent(country, forKey: .country)
    }
}

