//
// TitleGet200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TitleGet200Response: Codable, JSONEncodable, Hashable {

    public var docs: [TitleGet200ResponseDocsInner]
    public var total: Double
    public var limit: Double
    public var page: Double
    public var pages: Double

    public init(docs: [TitleGet200ResponseDocsInner], total: Double, limit: Double, page: Double, pages: Double) {
        self.docs = docs
        self.total = total
        self.limit = limit
        self.page = page
        self.pages = pages
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case docs
        case total
        case limit
        case page
        case pages
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(docs, forKey: .docs)
        try container.encode(total, forKey: .total)
        try container.encode(limit, forKey: .limit)
        try container.encode(page, forKey: .page)
        try container.encode(pages, forKey: .pages)
    }
}

