//
// TitleGet200ResponseDocsInnerPersonsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TitleGet200ResponseDocsInnerPersonsInner: Codable, JSONEncodable, Hashable {

    public var id: Double?
    public var photo: String?
    public var name: String?
    public var enName: String?
    public var description: String?
    public var profession: String?
    public var enProfession: String?

    public init(id: Double? = nil, photo: String? = nil, name: String? = nil, enName: String? = nil, description: String? = nil, profession: String? = nil, enProfession: String? = nil) {
        self.id = id
        self.photo = photo
        self.name = name
        self.enName = enName
        self.description = description
        self.profession = profession
        self.enProfession = enProfession
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case photo
        case name
        case enName
        case description
        case profession
        case enProfession
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(photo, forKey: .photo)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(enName, forKey: .enName)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(profession, forKey: .profession)
        try container.encodeIfPresent(enProfession, forKey: .enProfession)
    }
}

