//
// TitleGet200ResponseDocsInnerPremiere.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct TitleGet200ResponseDocsInnerPremiere: Codable, JSONEncodable, Hashable {

    public var country: String
    public var world: String
    public var russia: String
    public var digital: String
    public var cinema: String
    public var bluray: String
    public var dvd: String

    public init(country: String, world: String, russia: String, digital: String, cinema: String, bluray: String, dvd: String) {
        self.country = country
        self.world = world
        self.russia = russia
        self.digital = digital
        self.cinema = cinema
        self.bluray = bluray
        self.dvd = dvd
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case country
        case world
        case russia
        case digital
        case cinema
        case bluray
        case dvd
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(country, forKey: .country)
        try container.encode(world, forKey: .world)
        try container.encode(russia, forKey: .russia)
        try container.encode(digital, forKey: .digital)
        try container.encode(cinema, forKey: .cinema)
        try container.encode(bluray, forKey: .bluray)
        try container.encode(dvd, forKey: .dvd)
    }
}

